# Generated by Django 2.1 on 2018-10-01 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentmark', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='marked',
        ),
        migrations.AddField(
            model_name='submission',
            name='automark',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mark',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
