# Generated by Django 2.1 on 2018-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentmark', '0004_auto_20181002_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='autofeedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
