# Generated by Django 2.1 on 2018-10-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decentmark', '0006_submission_autostatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attempts',
        ),
    ]
