# Generated by Django 2.1.2 on 2018-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentmark', '0008_auto_20181005_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitusers',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
